arch: arm64
language: node_js
node_js:
  - '10'

services:
  - docker

env:
  global:
    - secure: "3XQ+rFJ3YTfl0SojuMQDmEt6O2FOA3Vj5z79byutUc72B+gByiHuV3UflhNKM/ftHpCe95syrNNu18oq6EaPgO/5A3Ec31BAjAInX43183v+d4VCegToyulloCTjE5Cj9wrf7+79wbHZ/3EkH5nJ36oRY5kE2KtXlEIbF54EnSfBEnWjerh5xzJRJCx5Xc/3+PNA9ajlmmFlSIMMRStsLbwHeQSfna7+e3I//spj9cpFVLZle7EsrAlBmc3hQenLebGHXu8XQYT08Q8fJAypokpxSSpuY/f9szTHSs9a1W8EGgoMqxoGrxRxf5t9Yrq2MSK6gRUlrFFIoZFl2RwBk59WZU2vdxMeRtCe0rA2aEBOSlzE7lzXrEyBio6DkX+jN3SM36DQ6kZMcZLaB6sLaDVA32N/fQaACkAMPo6NMGGpjRObAuOu45CwZdUgUY7TQqlpWvRPsny4ZxGqZE2ZEvxOtdb5e4qb1Jbr/++7ABC/wXTfPDJ2O3QQuPqkebEJAH3JITn14AALDsW5qZOYeuxLL3yCzOiIClP5z+fQcwqIMJxCtsISbh6mStJdKVVRzB2puIWwqnUpTJvkezMxcjmWRI7Gs2vi3O+4uiwGTNhDji58Pwowa3Iqfo7rExQjydwJV3nAstY1hEgVyjc8xLueJiPlrAB7Zn/a0JV12l0="
    - secure: "csdaJ7Ke9vT3PO6L9WA/4BtsFAGL3Q86ivFuCqpPxwV5dpDB2RBbHB2ClVTm5sDy23ML0JbieweT5jDj7LDs2hRQd1WPcAFCarO8yfWLrmRthjT9gas+Vd7karWwdoNmjMhT4qsONDuqJzxjYIySItxcdvg3Pru6uKgYOaMKNz0FFD7E/Pg/nd+7OtYqq/16evDlC6nR8O/5Htj8Qmm6ucwsvK17qAjZpVhm9acKh/hAEGiMa98jDuNbBaXqCVM+CTyp5DVxKTXhgvvE9bl4r3t1Z6oQz1UfIGAp9UdOUm31ze753+5CSNNXVJ98wCI2Nwpld6EKVdwWM80AntPvxUET7InpStCc4qFeqDzJW/vaFanO1FTVZQuZsXsarS4jV6xbQ8XVLQdAxX9SdZZw2rSqxtEfThDXJe/+it3f8DDFX8+H+lM0SZHzsba+PqXynTSaYr+p6zyaTdmXppOVrV4l00VlPE68hcZogyDbkjBx3RpDIClr6YunImN+v+6IFt3CK4tBzGBXYqwzrodP74EK8pWfsxbeUOTUlzR0D4jyeHkYdZGJXHys9xjkIPInzEAjcbz91xfOrCYNcj7blPIgOHg4I65wl5J8UlY0Fz0r9lVyDBsy/V7PySzk5fGEnAK9b4Ful35U0xCUdW7BvlgaId3mJ4EKITLUY2O+bWs="
    - secure: "1GKNsJt2AtPbmG6dSOY+kB1ABZwEzp7pS0bBfO6Vv+D7btPWEtUMNEgMleRz0VKWkU1gb//ORCCKQN/pmbEgwIgq706hv8zKjT342MoWNVetnq+VjOm4o1Gk0uQrUGzP7nGSalYC2KoPpt+1J6INf2xEQk6MpvzYpIQBY8aBCB7vJquMmnvpUW/wcQaB6bvndHUOC+1s0KY88III07Q+c3feI7MSTWZ7g3T7PCRAJGYKZhA9QIAFJ6WNmXjqfI90UdhEAIQrl7ggy0KrG5m+YtZv8Ei2D8o6kB8VCeFMN/k9V2PokNiG6KMt8qPi6WNOekQGvBJoV4qrSsZrKWSUZC29+vlGtNNgU0lbtq2GHoTPZ5x4A/LRpFPE+p2pwgqMvZypiXggTR3d7ruuwCFnpaD4USyMKnTAP300C+8bm5JZC9wL1ZDQpNCQ7mzkRhWoCHHgB4SbkCnq/udG75+Jqo7kSrLiDxGZ0jaAidlWbqbz/C0VVkPTQNseKBdXNhgIaubQyzIt0iOKEmP0jctpIQeYByjY/cSkwLBObSf1EgsIF4HU40bK7TdDNFVdFWdN8mdrH3SCQYKZWn7MdXgEmkmmY0OWo89jrymabpFtT33rW0Mqp930O7P1fN6SwrzdJv63Lfy+32+W5HPLPKXStQTj2+2yikg7bf+PPSBI2eA="

addons:
  sonarcloud:
    organization: cbartram-github

# Download Latest version of docker
#before_install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#  - docker --version

install: npm install

script:
  - npm test
  - npm run coverage
  - sh ./scripts/coding_style_tests.sh
  - sonar-scanner
after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

deploy:
  provider: script
  skip_cleanup: true
  script: sh ./scripts/deploy.sh
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"

cache:
  directories:
  - "$HOME/.npm"
  - "./node_modules"
  - "$HOME/.sonar/cache"

notifications:
  email: false